-- V15: 역제안(팀→유저). 팀장이 AI 추천 유저에게 제안을 보내고, 유저가 수락하면 즉시 팀원이 된다.
--
-- team_applications 와 방향이 반대인 별개의 실체다. 지원서는 "유저가 요청 → 팀장이 승인",
-- 제안은 "팀장이 요청 → 유저가 승인". 한 테이블에 방향 컬럼을 두어 합치지 않는 이유는
-- 상태 전이 주체와 권한 검증이 완전히 다르기 때문이다 — 합치면 모든 조회에 방향 분기가 붙는다.

CREATE TABLE team_offers (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id      bigint       NOT NULL,
    -- 제안을 받은 사람. 컬럼명을 target_user_id 가 아니라 user_id 로 두어
    -- team_applications.user_id 와 같은 자리에 오게 한다 (양쪽을 UNION 으로 볼 때 편하다).
    user_id      bigint       NOT NULL,
    message      text,                     -- 팀장이 쓴 제안 메시지 (선택)

    -- 제안 시점의 AI 추천 근거 스냅샷. team_to_user_recommendation_items 에서 복사해 온다.
    -- 참조가 아니라 복사인 이유: 추천은 호출할 때마다 점수가 달라지는데, 유저에게 보여준
    -- "왜 당신인가"는 제안을 보낸 그 순간의 것이어야 한다.
    -- 추천을 거치지 않고 보낸 제안도 허용하므로 nullable.
    ai_score     double precision,
    ai_label     text,

    status       varchar(20)  NOT NULL,    -- PENDING / ACCEPTED / REJECTED / CANCELED
    created_at   timestamp(6) NOT NULL,
    responded_at timestamp(6),             -- 유저가 응답했거나 팀장이 취소한 시각

    -- 한 팀이 같은 사람에게 두 번 제안할 수 없다. 애플리케이션 검증만 두면 동시 요청에서
    -- 뚫리므로 DB 에서 강제한다 (team_reviews.uq_team_reviews_pair 와 같은 사고방식).
    -- ※ 거절/취소 후 재제안도 이 제약에 막힌다. 의도된 것이다 — 재제안 스팸을 막는 게
    --   1차 목표고, 필요해지면 그때 partial unique (status='PENDING') 로 완화한다.
    CONSTRAINT uq_team_offers_pair UNIQUE (team_id, user_id)
);

-- 여기는 로그가 아니라 '현재 상태'라 FK 를 건다. 팀이나 유저가 사라지면 제안도 의미가 없다.
-- (V9 의 "FK 를 걸지 않는다"는 시점 기록 테이블에만 해당하는 규칙이다.)
ALTER TABLE team_offers
    ADD CONSTRAINT fk_team_offers_team FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE;
ALTER TABLE team_offers
    ADD CONSTRAINT fk_team_offers_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

-- "내가 받은 제안" — 유저 화면의 주 조회.
CREATE INDEX idx_team_offers_user ON team_offers (user_id, created_at DESC);
-- "이 팀이 보낸 제안" — 팀장 화면 + 추천 후보 제외 집합 계산.
CREATE INDEX idx_team_offers_team ON team_offers (team_id, created_at DESC);
