-- V16: 팀→유저 추천(POST /recommendations/team-to-user) 결과 로그. V9 의 방향만 뒤집은 쌍둥이다.
-- AI 서버는 stateless 이므로 "언제 어느 팀에게 누구를 왜 추천했는지"는 여기서만 남는다.
--
-- 여기엔 역할이 하나 더 있다: 팀장이 제안을 보낼 때 team_offers.ai_score/ai_label 을
-- 이 테이블에서 찾아 복사한다. 즉 프론트가 점수를 되보내지 않아도 되고, 되보낸 값을
-- 신뢰할 필요도 없다.

-- ── 헤더: 추천 호출 1건 ──────────────────────────────────────────────────────
CREATE TABLE team_to_user_recommendation_logs (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id              bigint  NOT NULL,       -- 추천을 요청한 팀 (질의 쪽)
    requested_by_user_id bigint  NOT NULL,       -- 요청 시점의 팀장. 팀장이 바뀌어도 누가 눌렀는지 남는다.
    candidate_count      integer NOT NULL,       -- AI 에 실제로 보낸 후보 수 (상한 적용 후)
    created_at           timestamp(6) NOT NULL
);

-- ── 아이템: 그 호출에서 나온 추천 결과 ───────────────────────────────────────
-- V9 와 같은 규약이다: 프론트에 내려간 상위 N 건만이 아니라 AI 가 점수를 매긴 결과 전체를
-- 순위대로 남긴다. team_id/user_id 에 FK 를 걸지 않는 이유와 rank 대신 rank_no 를 쓰는 이유도
-- V9 주석 참고 (시점 기록이라 팀/유저가 지워져도 남아야 한다).
CREATE TABLE team_to_user_recommendation_items (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id     bigint  NOT NULL,
    user_id    bigint  NOT NULL,                 -- 추천된 유저 (후보 쪽)
    rank_no    integer NOT NULL,                 -- 1 부터. 점수 내림차순 순위.
    score      double precision NOT NULL,
    label      text,                             -- AI 가 만든 추천 근거 문구
    created_at timestamp(6) NOT NULL,
    CONSTRAINT uk_team_to_user_recommendation_items_rank UNIQUE (log_id, rank_no)
);

-- 헤더가 지워지면 아이템도 함께 (아이템만 남으면 의미가 없다).
ALTER TABLE team_to_user_recommendation_items
    ADD CONSTRAINT fk_team_to_user_recommendation_items_log
    FOREIGN KEY (log_id) REFERENCES team_to_user_recommendation_logs (id) ON DELETE CASCADE;

-- ── 인덱스 ───────────────────────────────────────────────────────────────────
-- "이 팀에 최근 뭘 추천했나" 가 주 조회 패턴.
CREATE INDEX idx_team_to_user_recommendation_logs_team
    ON team_to_user_recommendation_logs (team_id, created_at DESC);
CREATE INDEX idx_team_to_user_recommendation_items_log
    ON team_to_user_recommendation_items (log_id, rank_no);
-- 제안 생성 시 (팀, 유저) 최신 추천 1건을 찾는 경로. user_id 단독으로는 못 쓰므로
-- log 조인 없이 좁히기 위해 user_id 를 선두로 둔다.
CREATE INDEX idx_team_to_user_recommendation_items_user
    ON team_to_user_recommendation_items (user_id, log_id DESC);
