-- V1 baseline: 클라우드 배포 DB의 현재 스키마 스냅샷 (pg_dump 기준).
-- 기존 데이터가 있는 클라우드 DB 는 baseline-on-migrate 로 "이미 적용됨" 처리되어
-- 이 파일이 실행되지 않는다. 빈 DB(로컬/신규 환경)는 이 파일로 동일한 시작
-- 스키마를 만든 뒤 V2 가 적용되어, 최종적으로 모든 환경이 엔티티와 일치한다.

CREATE TABLE email_verifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(6) NOT NULL,
    email varchar(100) NOT NULL,
    expires_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    verified boolean NOT NULL
);

CREATE TABLE events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_scope varchar(20),
    category varchar(20),
    created_at timestamp(6),
    description text,
    detail_url text,
    embedding_vector text,
    end_date date,
    external_id varchar(100) NOT NULL,
    image_url text,
    recommended_targets text,
    start_date date,
    summarized_description varchar(500),
    target_colleges varchar(255),
    title varchar(255),
    updated_at timestamp(6),
    CONSTRAINT events_external_id_key UNIQUE (external_id),
    CONSTRAINT events_campus_scope_check CHECK (campus_scope IN ('JUKJEON', 'CHEONAN', 'ALL')),
    CONSTRAINT events_category_check CHECK (category IN ('CONTEST', 'EXTERNAL', 'SCHOOL'))
);

CREATE TABLE notification (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content varchar(255),
    created_at timestamp(6),
    is_read boolean NOT NULL,
    title varchar(255),
    type varchar(255),
    user_id bigint,
    CONSTRAINT notification_type_check CHECK (type IN ('APPROVE', 'REJECT', 'INFO'))
);

CREATE TABLE oauth_debug_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(500) NOT NULL,
    created_at timestamp(6) NOT NULL
);

CREATE TABLE refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    email varchar(100) NOT NULL,
    expires_at timestamp(6) NOT NULL,
    token varchar(500) NOT NULL,
    CONSTRAINT refresh_tokens_token_key UNIQUE (token)
);

CREATE TABLE teams (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capacity integer,
    characteristic varchar(255),
    created_at timestamp(6),
    event_id bigint,
    is_recruiting boolean,
    leader_user_id bigint,
    promotion_text varchar(255),
    recruitment_end_date date,
    recruitment_start_date date,
    role varchar(255),
    title varchar(255),
    updated_at timestamp(6)
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus varchar(20),
    college varchar(100),
    created_at timestamp(6) NOT NULL,
    dreamy_report text,
    email varchar(100) NOT NULL,
    grade varchar(10),
    interest_job_primary varchar(100),
    interest_job_secondary varchar(100),
    interest_job_tertiary varchar(100),
    major varchar(100),
    name varchar(50) NOT NULL,
    password varchar(255) NOT NULL,
    tagline varchar(200),
    updated_at timestamp(6) NOT NULL,
    provider_id varchar(100),
    school_email varchar(100),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_school_email_key UNIQUE (school_email),
    CONSTRAINT users_campus_check CHECK (campus IN ('JUKJEON', 'CHEONAN'))
);

CREATE TABLE team_applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_number varchar(20),
    created_at timestamp(6),
    introduction varchar(255),
    message text,
    portfolio_url varchar(500),
    status varchar(255) NOT NULL,
    user_id bigint NOT NULL,
    team_id bigint NOT NULL,
    CONSTRAINT team_applications_status_check CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

ALTER TABLE team_applications
    ADD CONSTRAINT fk_team_applications_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE team_applications
    ADD CONSTRAINT fk_team_applications_team FOREIGN KEY (team_id) REFERENCES teams (id);
ALTER TABLE notification
    ADD CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users (id);
