-- V24: 활동 북마크(즐겨찾기). 유저가 공모전/대외활동을 찜해 두고 나중에 다시 본다.
--
-- events 에 컬럼을 붙이지 않고 별도 테이블로 두는 이유: events 는 크롤러가 대량으로 쓰는
-- 테이블이고 북마크는 유저가 한 건씩 쓰는 데이터라 쓰기 패턴이 완전히 다르다
-- (user_embeddings 를 users 에 합치지 않은 것과 같은 판단).
--
-- 대상은 활동뿐이다. 팀 모집글 북마크가 필요해지면 team_bookmarks 를 따로 만든다 —
-- (user_id, target_type, target_id) 형태의 다형 테이블 하나로 합치면 FK 를 걸 수 없어
-- 무결성이 통째로 애플리케이션 책임이 된다.

CREATE TABLE event_bookmarks (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL,
    event_id   bigint       NOT NULL,
    created_at timestamp(6) NOT NULL,

    -- 같은 활동을 두 번 찜할 수 없다. 애플리케이션 검사만으로는 동시 요청(별 아이콘 더블클릭)에서
    -- 뚫리므로 DB 에서 강제한다 (uq_team_offers_pair 와 같은 사고방식).
    -- ※ 다만 여기서는 중복 요청을 에러로 돌려주지 않는다. 재제안 스팸을 막는 게 목적인 team_offers 와
    --   달리, 북마크는 같은 버튼을 두 번 누르는 게 정상 UX 라 결과 상태만 같으면 된다
    --   (BookmarkService.addBookmark 참고).
    CONSTRAINT uq_event_bookmarks_pair UNIQUE (user_id, event_id)
);

-- 로그가 아니라 '현재 상태'라 FK 를 건다. 유저나 활동이 사라지면 북마크도 의미가 없다.
-- (V9 의 "FK 를 걸지 않는다"는 시점 기록 테이블에만 해당하는 규칙이다.)
ALTER TABLE event_bookmarks
    ADD CONSTRAINT fk_event_bookmarks_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE event_bookmarks
    ADD CONSTRAINT fk_event_bookmarks_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE;

-- "내 북마크 목록" — 주 조회. 북마크한 최신순 정렬을 인덱스로 그대로 태운다.
-- 활동 시작일순이 아니라 찜한 순서다(늦게 찜한 오래된 공고가 위에 온다).
CREATE INDEX idx_event_bookmarks_user ON event_bookmarks (user_id, created_at DESC);

-- 검색 응답의 bookmarked 채우기(user_id = ? AND event_id IN (...))는 uq_event_bookmarks_pair 의
-- 유니크 인덱스가 그대로 커버하므로 별도 인덱스를 두지 않는다.
