-- V25: 포트폴리오 PDF 요약 캐시.
--
-- AI 서버(/portfolios/summarize)는 상태가 없고, 돌려주는 pdf_id 는 채번값이 아니라
-- PDF 원본 바이트의 SHA-256 이다. 즉 같은 파일이면 언제 올려도 같은 값이 나온다.
-- 이 테이블은 그 성질을 이용해 "이미 요약해 본 PDF 인가"를 판정하는 캐시다 —
-- 15페이지를 렌더링해 Vision 한 번을 태우는 호출이라 재업로드마다 다시 부를 이유가 없다.
--
-- users 에 컬럼을 붙이지 않는 이유는 V24(event_bookmarks) 와 같다. 한 사람이 여러 버전의
-- 포트폴리오를 올릴 수 있어 1:N 이고, 쓰기 시점도 프로필 수정과 전혀 다르다.

CREATE TABLE user_portfolios (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL,
    -- PDF 원본 바이트의 SHA-256 (소문자 hex 64자). 길이가 고정이지만 char(64) 가 아닌 이유:
    -- char 는 비교 시 공백을 덧대는 blank-padded 타입이고, Postgres 가 bpchar 로 보고해
    -- ddl-auto=validate 의 varchar 기대와 어긋난다. 고정 길이로 얻을 이점도 없다.
    pdf_id     varchar(64)  NOT NULL,
    -- AI 가 만든 마크다운 원문(불릿 목록 + '요약' 문단). 백엔드는 해석하지 않고 그대로 보관한다.
    -- 길이 상한을 두지 않는 이유: LLM 출력이라 우리가 정한 상한을 넘으면 저장이 통째로 실패하는데,
    -- 그 시점엔 이미 Vision 호출 비용을 쓴 뒤다.
    summary    text         NOT NULL,
    -- 사용자가 올린 원본 파일명. 표시/디버깅용이며 신뢰하지 않는다(경로·확장자 모두 클라이언트 값).
    filename   varchar(255),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,

    -- 캐시 키. pdf_id 만으로 전역 유니크를 걸지 않는 이유: 두 사람이 같은 파일을 올릴 수 있고,
    -- 그때 남의 행을 덮어쓰거나 남의 요약을 보게 되면 안 된다(포트폴리오는 개인 이력이다).
    -- 같은 PDF 를 동시에 두 번 올리는 경합도 이 제약이 막는다
    -- (PortfolioSummaryService 는 event_bookmarks 와 같이 위반을 잡아 기존 요약을 돌려준다).
    CONSTRAINT uq_user_portfolios_pair UNIQUE (user_id, pdf_id)
);

-- 로그가 아니라 '현재 보유한 요약'이라 FK 를 건다. 탈퇴하면 함께 사라져야 한다.
ALTER TABLE user_portfolios
    ADD CONSTRAINT fk_user_portfolios_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

-- 조회는 항상 (user_id, pdf_id) 동등 조건이라 uq_user_portfolios_pair 의 유니크 인덱스가
-- 그대로 커버한다. 별도 인덱스를 두지 않는다.
