-- V29: 사용자가 직접 쓰는 포트폴리오 서술.
--
-- 이름이 겹치는 기존 두 가지와 다른 값이다.
--   * user_portfolios (V25): PDF 를 올리면 AI 가 만들어 주는 요약. 1:N 이고 사람이 쓰는 값이 아니다.
--   * team_applications.portfolio_url: 팀 지원서에 첨부하는 링크. 지원서 단위 값이지 프로필 값이 아니다.
-- 이 컬럼은 프로필의 일부로, 사용자가 프로필 수정 화면에서 여러 줄로 직접 타이핑한다.
-- 한 줄 소개인 tagline(varchar 200) 으로는 담기지 않아 따로 둔다.
--
-- 길이 제한을 두지 않는 이유: 몇 자가 적당한지는 화면 사정이라 바뀌기 쉬운데, varchar(N) 으로
-- 박아 두면 그때마다 마이그레이션이 필요하다. 상한은 UserUpdateRequest 의 @Size 로 잡는다 —
-- 거기 숫자는 요청 본문 상한일 뿐이라 마이그레이션 없이 조정된다.
ALTER TABLE users ADD COLUMN portfolio text;
