-- V30: AI 대화 통합 로그.
--
-- 배경: AI 게이트웨이가 도메인을 분류한 뒤 서버에서 곧장 도메인 서비스로 위임한다. 이때
-- 게이트웨이와 도메인 서비스가 각자 대화를 기록하면 같은 발화가 두 벌 남는다. 그래서 대화
-- 로그를 여기 한 곳으로 모으고, matching_intent_messages 는 이 테이블로 이관한다.
--
-- 통합하는 것과 남기는 것을 구분했다:
--   - 통합: 누가·언제·무슨 말을 했는가 (도메인이 늘어도 컬럼이 변하지 않는다)
--   - 도메인 유지: 진행 상태·추출 결과·만료 판정 (matching_intent_sessions 가 계속 갖는다)
--     이걸 여기 넣으면 한 도메인만 쓰는 nullable 컬럼이 도메인마다 붙는다.

-- ── ai_conversations: 대화 스레드 ────────────────────────────────────────────
CREATE TABLE ai_conversations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    status varchar(20) NOT NULL,              -- ACTIVE / CLOSED
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT ai_conversations_status_check CHECK (status IN ('ACTIVE', 'CLOSED'))
);

-- ── ai_conversation_messages: 대화 한 줄 ─────────────────────────────────────
-- domain / domain_ref_id 가 이 설계의 핵심이다.
--   - 둘 다 NULL: 게이트웨이가 혼자 처리한 턴 (되묻기, 범위 밖 안내).
--     화면 복원에는 쓰이되 도메인 AI 로는 보내지 않는다.
--   - 채워짐: 그 도메인 세션 소관. 도메인 AI 로 보낼 배열은 domain_ref_id 로 정확히 걸러진다.
--
-- domain 만으로 거르면 안 되는 이유: 한 대화 안에서 매칭 세션이 완료·만료되고 새 세션이
-- 열릴 수 있다. 그때 옛 세션의 발화가 새 세션에 딸려 가면 추출 결과가 오염된다.
CREATE TABLE ai_conversation_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id bigint NOT NULL,
    seq integer NOT NULL,
    role varchar(10) NOT NULL,                -- USER / ASSISTANT
    content text NOT NULL,
    domain varchar(30),                       -- NULL = 게이트웨이 자체 턴
    domain_ref_id bigint,                     -- 도메인 세션 id (매칭이면 matching_intent_sessions.id)
    created_at timestamp(6) NOT NULL,
    CONSTRAINT ai_conversation_messages_role_check CHECK (role IN ('USER', 'ASSISTANT')),
    -- 위임할 곳이 있는 도메인만 저장된다. 도메인을 추가하면 여기도 함께 넓혀야 한다
    -- (RoutableDomain 에 상수만 늘리고 마이그레이션을 잊는 사고를 DB 가 막아 준다).
    CONSTRAINT ai_conversation_messages_domain_check
        CHECK (domain IS NULL OR domain IN ('MATCHING_INTENT')),
    -- domain 과 domain_ref_id 는 함께 있거나 함께 없다. 한쪽만 채워지면 필터가 조용히 어긋난다.
    CONSTRAINT ai_conversation_messages_domain_ref_check
        CHECK ((domain IS NULL) = (domain_ref_id IS NULL)),
    CONSTRAINT uk_ai_conversation_messages_seq UNIQUE (conversation_id, seq)
);

ALTER TABLE ai_conversations
    ADD CONSTRAINT fk_ai_conversations_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE ai_conversation_messages
    ADD CONSTRAINT fk_ai_conversation_messages_conversation
        FOREIGN KEY (conversation_id) REFERENCES ai_conversations (id);

-- ── 매칭 세션을 대화에 묶는다 ────────────────────────────────────────────────
ALTER TABLE matching_intent_sessions ADD COLUMN conversation_id bigint;

-- ── 기존 데이터 이관 ─────────────────────────────────────────────────────────
-- INSERT ... SELECT 는 "새로 생긴 id ↔ 원본 행"의 대응을 돌려주지 않는다. 임시 컬럼에
-- 원본 세션 id 를 실어 두고 그걸로 조인한 뒤 지운다.
ALTER TABLE ai_conversations ADD COLUMN migration_session_id bigint;

-- 세션 1건 → 대화 1건. 진행 중이던 세션의 대화만 ACTIVE 로 남는다.
INSERT INTO ai_conversations (user_id, status, created_at, updated_at, migration_session_id)
SELECT s.user_id,
       CASE WHEN s.status = 'IN_PROGRESS' THEN 'ACTIVE' ELSE 'CLOSED' END,
       s.created_at,
       s.updated_at,
       s.id
FROM matching_intent_sessions s;

UPDATE matching_intent_sessions s
SET conversation_id = c.id
FROM ai_conversations c
WHERE c.migration_session_id = s.id;

-- 메시지 전 행을 옮긴다. 전부 매칭 소관이고, 그 세션이 곧 domain_ref_id 다.
INSERT INTO ai_conversation_messages
    (conversation_id, seq, role, content, domain, domain_ref_id, created_at)
SELECT c.id, m.seq, m.role, m.message, 'MATCHING_INTENT', m.session_id, m.created_at
FROM matching_intent_messages m
JOIN ai_conversations c ON c.migration_session_id = m.session_id;

ALTER TABLE ai_conversations DROP COLUMN migration_session_id;

-- 이관이 끝났으니 NOT NULL 을 건다. 빠진 행이 있으면 여기서 배포가 멈춘다 —
-- conversation_id 가 NULL 로 남은 세션은 앱이 조용히 깨지는 쪽이라 그편이 낫다.
ALTER TABLE matching_intent_sessions ALTER COLUMN conversation_id SET NOT NULL;
ALTER TABLE matching_intent_sessions
    ADD CONSTRAINT fk_matching_intent_sessions_conversation
        FOREIGN KEY (conversation_id) REFERENCES ai_conversations (id);

-- ※ matching_intent_messages 는 여기서 지우지 않는다. 운영 데이터가 실려 있고, 이관 결과를
--   눈으로 확인한 뒤 별도 마이그레이션에서 드롭한다. 엔티티는 이미 제거돼 있으므로
--   Hibernate ddl-auto=validate 는 이 잉여 테이블을 문제 삼지 않는다.

-- ── 인덱스 ───────────────────────────────────────────────────────────────────
CREATE INDEX idx_ai_conversations_user ON ai_conversations (user_id, id);
CREATE INDEX idx_ai_conv_msg_conversation ON ai_conversation_messages (conversation_id, seq);
CREATE INDEX idx_ai_conv_msg_domain_ref ON ai_conversation_messages (domain, domain_ref_id, seq);

-- 사용자당 ACTIVE 대화는 최대 1개. 부분 유니크 인덱스로 DB 가 보장한다.
-- (Hibernate validate 는 부분 인덱스를 검사하지 않으므로 엔티티에는 선언하지 않는다.
--  matching_intent_sessions 의 IN_PROGRESS 도 같은 방식이라 이관 데이터가 이걸 어길 수 없다)
CREATE UNIQUE INDEX uk_ai_conversations_active
    ON ai_conversations (user_id) WHERE status = 'ACTIVE';
