-- V31: 멀티 스레드 AI 채팅 + 도메인 작업 층.
--
-- 배경: V30 의 모델은 "사용자당 살아 있는 대화 1개"였고, 메시지는 (domain, domain_ref_id) 라는
-- 다형 포인터로 도메인 세션을 가리켰다. 화면이 하나고 도메인이 하나일 때는 충분했다.
--
-- 이번에 두 가지가 정해졌다:
--   1) 프론트에 대화 목록(사이드바)이 생긴다. 사용자가 스레드를 여러 개 갖고 골라 들어간다.
--   2) 한 스레드 안에서 도메인 작업이 두 번 이상 일어날 수 있다.
--
-- 그래서 층을 둘로 가른다.
--
--   ai_chat_sessions ─1:N─ ai_domain_tasks ─1:1─ matching_intent_sessions
--          │ 1                    │ 1
--          │                      │
--          N                      N   ← task_id 는 NULL 허용 (게이트웨이 자체 턴)
--          └──── ai_chat_messages ┘
--
-- 핵심은 **수명 상태를 ai_domain_tasks 하나만 갖는다**는 것이다. matching_intent_sessions.status
-- 의 네 값(IN_PROGRESS/COMPLETED/ABANDONED/EXPIRED)은 전부 "살아 있나 / 왜 끝났나"라서 매칭
-- 고유의 사실이 하나도 없다. 둘 다 두면 "이 작업이 살아 있나"의 답이 두 곳에 생기고, 한 번
-- 어긋나면 게이트웨이는 진행 중으로 보고 통과시키는데 매칭은 없다고 보고 새 작업을 연다.
-- 예외도 안 나고 테스트도 안 깨지는 종류라, 아예 한 곳으로 모은다.
-- (프론트가 보는 status 값은 그대로다 — 애플리케이션이 두 컬럼에서 1:1 로 복원해 준다)

-- ── 1. 개명 ──────────────────────────────────────────────────────────────────
-- "conversation" 은 사용자 어휘가 아니다. 사이드바에서 고르는 그것을 사용자는 세션이라 부른다.
-- V30 이 만든 지 얼마 안 됐고 운영 배포 전이라 데이터 이동 없이 이름만 바꾼다.
ALTER TABLE ai_conversations RENAME TO ai_chat_sessions;
ALTER TABLE ai_conversation_messages RENAME TO ai_chat_messages;
ALTER TABLE ai_chat_messages RENAME COLUMN conversation_id TO chat_session_id;

ALTER TABLE ai_chat_sessions RENAME CONSTRAINT fk_ai_conversations_user TO fk_ai_chat_sessions_user;
ALTER TABLE ai_chat_messages
    RENAME CONSTRAINT fk_ai_conversation_messages_conversation TO fk_ai_chat_messages_session;
ALTER TABLE ai_chat_messages
    RENAME CONSTRAINT ai_conversation_messages_role_check TO ai_chat_messages_role_check;
ALTER TABLE ai_chat_messages
    RENAME CONSTRAINT uk_ai_conversation_messages_seq TO uk_ai_chat_messages_seq;
ALTER INDEX idx_ai_conv_msg_conversation RENAME TO idx_ai_chat_msg_session;

-- ── 2. 스레드에서 status 를 걷어낸다 ─────────────────────────────────────────
-- "사용자당 ACTIVE 1건"은 화면이 하나일 때의 개념이다. 스레드를 골라 들어갈 수 있게 되면
-- 어디에 쓸지는 사용자가 정하므로 이 상태 자체가 의미를 잃는다.
DROP INDEX uk_ai_conversations_active;
DROP INDEX idx_ai_conversations_user;
ALTER TABLE ai_chat_sessions DROP CONSTRAINT ai_conversations_status_check;
ALTER TABLE ai_chat_sessions DROP COLUMN status;

-- 사이드바에 보여 줄 제목. 첫 사용자 발화 앞부분을 잘라 쓴다 (LLM 호출은 하지 않는다).
ALTER TABLE ai_chat_sessions ADD COLUMN title varchar(100);

-- seq 채번을 카운터로. 지금은 메시지를 붙일 때마다 COUNT(*) 를 도는데, 스레드가 길어질수록
-- 비용이 늘고 무엇보다 ai_chat_sessions 행을 건드리지 않아 updated_at 이 생성 시각에 멈춘다.
-- 사이드바 정렬 키가 그 컬럼이므로 정직해야 한다.
ALTER TABLE ai_chat_sessions ADD COLUMN last_seq integer NOT NULL DEFAULT 0;

UPDATE ai_chat_sessions c
SET last_seq = COALESCE(
        (SELECT max(m.seq) FROM ai_chat_messages m WHERE m.chat_session_id = c.id), 0);

UPDATE ai_chat_sessions c
SET title = left(m.content, 40)
FROM (SELECT DISTINCT ON (chat_session_id) chat_session_id, content
      FROM ai_chat_messages
      WHERE role = 'USER'
      ORDER BY chat_session_id, seq) m
WHERE m.chat_session_id = c.id;

ALTER TABLE ai_chat_sessions ALTER COLUMN last_seq DROP DEFAULT;

-- ── 3. ai_domain_tasks: 도메인 작업 한 판 ────────────────────────────────────
CREATE TABLE ai_domain_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_session_id bigint NOT NULL,
    -- user_id 는 chat_session 을 거치면 알 수 있지만 비정규화한다. 아래 부분 유니크 인덱스가
    -- "사용자당 도메인당 진행 중 1건"을 보장해야 하는데, 부분 인덱스는 테이블을 건널 수 없다.
    user_id bigint NOT NULL,
    domain varchar(30) NOT NULL,
    status varchar(20) NOT NULL,              -- ACTIVE / CLOSED
    closed_reason varchar(20),                -- COMPLETED / ABANDONED / EXPIRED
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,         -- 마지막 활동 시각 = 지연 만료 판정 기준
    closed_at timestamp(6),
    CONSTRAINT ai_domain_tasks_status_check
        CHECK (status IN ('ACTIVE', 'CLOSED')),
    -- 위임할 곳이 있는 도메인만 작업을 갖는다. 도메인을 추가하면 여기도 함께 넓혀야 한다
    -- (RoutableDomain 에 상수만 늘리고 마이그레이션을 잊는 사고를 DB 가 막아 준다).
    CONSTRAINT ai_domain_tasks_domain_check
        CHECK (domain IN ('MATCHING_INTENT')),
    CONSTRAINT ai_domain_tasks_reason_check
        CHECK (closed_reason IS NULL
               OR closed_reason IN ('COMPLETED', 'ABANDONED', 'EXPIRED')),
    -- 닫힌 작업은 사유와 시각을 반드시 갖고, 열린 작업은 반드시 안 갖는다. 한쪽만 채워지면
    -- "왜 끝났는지 모르는 종료"나 "닫힌 줄 모르는 작업"이 생긴다.
    CONSTRAINT ai_domain_tasks_closed_check
        CHECK ((status = 'CLOSED') = (closed_reason IS NOT NULL)
               AND (status = 'CLOSED') = (closed_at IS NOT NULL))
);

ALTER TABLE ai_domain_tasks
    ADD CONSTRAINT fk_ai_domain_tasks_session
        FOREIGN KEY (chat_session_id) REFERENCES ai_chat_sessions (id);
ALTER TABLE ai_domain_tasks
    ADD CONSTRAINT fk_ai_domain_tasks_user FOREIGN KEY (user_id) REFERENCES users (id);

-- ── 4. 작업 백필 ─────────────────────────────────────────────────────────────
-- V30 과 같은 수법 — INSERT ... SELECT 는 "새 id ↔ 원본 행" 대응을 돌려주지 않으므로 임시
-- 컬럼에 원본 id 를 실어 두고 조인한 뒤 지운다.
ALTER TABLE ai_domain_tasks ADD COLUMN migration_matching_id bigint;

-- 매칭 세션 1건 → 작업 1건. status 를 (status, closed_reason, closed_at) 으로 풀어 옮긴다.
-- closed_at 은 ABANDONED/EXPIRED 에 한해 근사값이다 — 종료 시각을 기록한 적이 없어
-- updated_at 으로 대신한다. 방치·포기 뒤에는 갱신될 일이 없어 실제와 거의 같다.
INSERT INTO ai_domain_tasks
    (chat_session_id, user_id, domain, status, closed_reason,
     created_at, updated_at, closed_at, migration_matching_id)
SELECT s.conversation_id,
       s.user_id,
       'MATCHING_INTENT',
       CASE WHEN s.status = 'IN_PROGRESS' THEN 'ACTIVE' ELSE 'CLOSED' END,
       CASE WHEN s.status = 'IN_PROGRESS' THEN NULL ELSE s.status END,
       s.created_at,
       s.updated_at,
       CASE WHEN s.status = 'IN_PROGRESS' THEN NULL
            ELSE COALESCE(s.completed_at, s.updated_at) END,
       s.id
FROM matching_intent_sessions s;

-- ── 5. 메시지의 다형 포인터를 FK 로 교체 ────────────────────────────────────
ALTER TABLE ai_chat_messages ADD COLUMN task_id bigint;

UPDATE ai_chat_messages m
SET task_id = t.id
FROM ai_domain_tasks t
WHERE m.domain = 'MATCHING_INTENT'
  AND t.migration_matching_id = m.domain_ref_id;

-- 도장이 찍혀 있었는데 작업을 못 찾은 행이 있으면 여기서 배포를 멈춘다. 그대로 두면 그 발화가
-- 도메인 AI 로 보낼 배열에서 통째로 빠져 대화가 제자리를 맴돈다 — 조용히 깨지는 쪽이다.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM ai_chat_messages
               WHERE domain IS NOT NULL AND task_id IS NULL) THEN
        RAISE EXCEPTION 'V31 이관 실패: 도메인 도장이 있는데 작업을 못 찾은 메시지가 있다';
    END IF;
END $$;

ALTER TABLE ai_chat_messages DROP CONSTRAINT ai_conversation_messages_domain_check;
ALTER TABLE ai_chat_messages DROP CONSTRAINT ai_conversation_messages_domain_ref_check;
DROP INDEX idx_ai_conv_msg_domain_ref;

ALTER TABLE ai_chat_messages DROP COLUMN domain;
ALTER TABLE ai_chat_messages DROP COLUMN domain_ref_id;

ALTER TABLE ai_chat_messages
    ADD CONSTRAINT fk_ai_chat_messages_task FOREIGN KEY (task_id) REFERENCES ai_domain_tasks (id);

-- ── 6. 매칭 세션을 작업에 매단다 ────────────────────────────────────────────
ALTER TABLE matching_intent_sessions ADD COLUMN task_id bigint;

UPDATE matching_intent_sessions s
SET task_id = t.id
FROM ai_domain_tasks t
WHERE t.migration_matching_id = s.id;

-- 빠진 행이 있으면 여기서 멈춘다 (V30 의 conversation_id 와 같은 이유).
ALTER TABLE matching_intent_sessions ALTER COLUMN task_id SET NOT NULL;
-- 1:1 이다. 작업 하나는 domain 컬럼으로 도메인이 정해져 있으니 부속 행도 하나뿐이다.
ALTER TABLE matching_intent_sessions
    ADD CONSTRAINT uk_matching_intent_sessions_task UNIQUE (task_id);
ALTER TABLE matching_intent_sessions
    ADD CONSTRAINT fk_matching_intent_sessions_task
        FOREIGN KEY (task_id) REFERENCES ai_domain_tasks (id);

-- 수명은 위로 올라갔다. 남겨 두면 "살아 있나"의 답이 두 곳에 생긴다.
DROP INDEX uk_matching_intent_sessions_active;
ALTER TABLE matching_intent_sessions
    DROP CONSTRAINT matching_intent_sessions_status_check;
ALTER TABLE matching_intent_sessions DROP COLUMN status;

-- conversation_id 도 필요 없다 — 작업을 거쳐 스레드에 도달한다. 경로가 둘이면 어긋날 수 있다.
ALTER TABLE matching_intent_sessions
    DROP CONSTRAINT fk_matching_intent_sessions_conversation;
ALTER TABLE matching_intent_sessions DROP COLUMN conversation_id;

ALTER TABLE ai_domain_tasks DROP COLUMN migration_matching_id;

-- ── 7. 인덱스 ────────────────────────────────────────────────────────────────
-- 사이드바는 사용자별로 최근 순이다.
CREATE INDEX idx_ai_chat_sessions_user ON ai_chat_sessions (user_id, updated_at DESC);
CREATE INDEX idx_ai_domain_tasks_session ON ai_domain_tasks (chat_session_id, id);
CREATE INDEX idx_ai_chat_msg_task ON ai_chat_messages (task_id, seq);

-- 진행 중인 작업은 사용자당 도메인당 1개. V7 의 uk_matching_intent_sessions_active 가 주던
-- 보장을 그대로 이어받는다. 스레드당이 아니라 사용자당인 이유는 매칭 슬롯이 사용자당 1건이라,
-- 두 스레드에서 동시에 매칭하면 같은 슬롯을 두고 싸우기 때문이다.
-- (Hibernate validate 는 부분 인덱스를 검사하지 않으므로 엔티티에는 선언하지 않는다)
CREATE UNIQUE INDEX uk_ai_domain_tasks_active
    ON ai_domain_tasks (user_id, domain) WHERE status = 'ACTIVE';
