-- 비밀번호 찾기 매직링크. raw 토큰은 메일·웹 쿼리에만 두고 DB 에는 SHA-256 해시만 둔다.
-- 링크가 로그·Referer 에 남을 수 있어서 인증코드처럼 평문을 저장하지 않는다.

CREATE TABLE password_reset_tokens (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash varchar(64)  NOT NULL,
    expires_at timestamp    NOT NULL,
    used_at    timestamp,
    created_at timestamp    NOT NULL,
    CONSTRAINT uq_password_reset_tokens_hash UNIQUE (token_hash)
);

CREATE INDEX idx_password_reset_tokens_user ON password_reset_tokens (user_id, created_at DESC);
