-- V3: 채팅 기능(WebSocket/STOMP) 테이블 추가 (커밋 12fe3df)
-- ChatRoom / ChatRoomMember / ChatMessage 엔티티에 맞춘 스키마.

-- ── chat_rooms: 대화방 (DM / GROUP) ──────────────────────────────────────────
CREATE TABLE chat_rooms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type varchar(20) NOT NULL,          -- RoomType (DM / GROUP)
    team_id bigint,                     -- GROUP 방이 Team 과 연결될 때. DM 은 NULL.
    title varchar(100),                 -- GROUP 방 이름. DM 은 NULL.
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,   -- 새 메시지마다 갱신 → 방 목록 최신순 정렬
    CONSTRAINT chat_rooms_type_check CHECK (type IN ('DM', 'GROUP'))
);

-- ── chat_room_members: 방 참여자 + 읽음 위치 ─────────────────────────────────
CREATE TABLE chat_room_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id bigint NOT NULL,
    user_id bigint NOT NULL,
    last_read_message_id bigint,        -- 마지막으로 읽은 메시지 id. NULL 이면 미열람.
    joined_at timestamp(6) NOT NULL,
    CONSTRAINT uk_chat_room_member UNIQUE (room_id, user_id)
);

-- ── chat_messages: 메시지 ────────────────────────────────────────────────────
CREATE TABLE chat_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) NOT NULL
);

-- ── 외래키 ───────────────────────────────────────────────────────────────────
ALTER TABLE chat_room_members
    ADD CONSTRAINT fk_chat_room_members_room FOREIGN KEY (room_id) REFERENCES chat_rooms (id);
ALTER TABLE chat_room_members
    ADD CONSTRAINT fk_chat_room_members_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE chat_messages
    ADD CONSTRAINT fk_chat_messages_room FOREIGN KEY (room_id) REFERENCES chat_rooms (id);
ALTER TABLE chat_messages
    ADD CONSTRAINT fk_chat_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id);

-- ── 인덱스 (ChatMessage @Index: room_id, id) ─────────────────────────────────
CREATE INDEX idx_chat_messages_room_id ON chat_messages (room_id, id);
