-- V7: 제안 기능(USER_TO_TEAM) 의도 추출 대화 세션 + 추출 슬롯.
-- AI 서버(POST /intents/extract)는 stateless 이므로 대화 이력은 전적으로 여기서 보관한다.

-- ── matching_intent_sessions: 사용자당 진행 중인 의도 추출 대화 1건 ──────────
CREATE TABLE matching_intent_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    status varchar(20) NOT NULL,              -- IN_PROGRESS / COMPLETED / ABANDONED / EXPIRED
    last_missing_fields text,                 -- 마지막 AI 응답의 missing_fields (CSV). 완료 시 빈값.
    last_extracted_json text,                 -- 마지막 AI 응답의 extracted 원본. 세션 복원용.
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,         -- 갱신 시각 = 지연 만료 판정 기준
    completed_at timestamp(6),
    CONSTRAINT matching_intent_sessions_status_check
        CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'ABANDONED', 'EXPIRED'))
);

-- ── matching_intent_messages: 대화 이력 ──────────────────────────────────────
-- USER 발화와 AI 의 assistant_message 를 둘 다 한 테이블에 시간순으로 쌓는다.
-- assistant_message 는 대화의 한 턴이므로 여기가 제 자리다 (프론트 대화 복원·표시용).
--
-- ※ 저장과 전송은 다르다:
--   - 저장: USER + ASSISTANT 둘 다
--   - FastAPI 전송: USER 만. 명세가 messages 를 "사용자가 한 말"로 정의했고,
--     요청 예시에서도 AI 질문은 배열에 없다.
-- seq 는 정렬 키일 뿐이다. AI 는 messages[].id 가 1부터 연속 증가하길 요구하므로,
-- 전송 시 USER 행만 골라 1..N 으로 재채번한다 (seq 를 그대로 보내지 않는다).
CREATE TABLE matching_intent_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL,
    seq integer NOT NULL,
    role varchar(10) NOT NULL,                -- USER / ASSISTANT
    message text NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT matching_intent_messages_role_check CHECK (role IN ('USER', 'ASSISTANT')),
    CONSTRAINT uk_matching_intent_messages_seq UNIQUE (session_id, seq)
);

-- ── matching_intent_slots: 추출 완료된 의도 (사용자당 1건, upsert) ───────────
-- embedding_vector 는 여기가 아니라 user_embeddings (V6) 에 저장된다.
CREATE TABLE matching_intent_slots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    session_id bigint NOT NULL,
    desired_roles text,                       -- CSV (StringListConverter)
    skills text,                              -- CSV
    interests text,                           -- CSV
    activity_goal varchar(255),
    activity_style varchar(255),
    experience_level varchar(50),
    embedding_text text,                      -- 임베딩의 원문 (벡터 아님)
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT uk_matching_intent_slots_user UNIQUE (user_id)
);

-- ── 외래키 ───────────────────────────────────────────────────────────────────
ALTER TABLE matching_intent_sessions
    ADD CONSTRAINT fk_matching_intent_sessions_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE matching_intent_messages
    ADD CONSTRAINT fk_matching_intent_messages_session FOREIGN KEY (session_id) REFERENCES matching_intent_sessions (id);
ALTER TABLE matching_intent_slots
    ADD CONSTRAINT fk_matching_intent_slots_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE matching_intent_slots
    ADD CONSTRAINT fk_matching_intent_slots_session FOREIGN KEY (session_id) REFERENCES matching_intent_sessions (id);

-- ── 인덱스 ───────────────────────────────────────────────────────────────────
CREATE INDEX idx_matching_intent_messages_session ON matching_intent_messages (session_id, seq);
CREATE INDEX idx_matching_intent_sessions_user ON matching_intent_sessions (user_id, id);

-- 사용자당 IN_PROGRESS 세션은 최대 1개. 부분 유니크 인덱스로 DB 가 보장한다.
-- (Hibernate validate 는 부분 인덱스를 검사하지 않으므로 엔티티에는 선언하지 않는다)
CREATE UNIQUE INDEX uk_matching_intent_sessions_active
    ON matching_intent_sessions (user_id) WHERE status = 'IN_PROGRESS';
