-- V9: 유저→팀 추천(POST /recommendations/user-to-team) 결과 로그.
-- AI 서버는 stateless 이므로 "언제 누구에게 무엇을 왜 추천했는지"는 여기서만 남는다.
-- 추천 품질 튜닝(어떤 label 이 실제 지원으로 이어졌나)의 근거 데이터가 된다.

-- ── 헤더: 추천 호출 1건 ──────────────────────────────────────────────────────
CREATE TABLE user_to_team_recommendation_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    event_id bigint,                          -- eventId 필터로 좁힌 경우에만. 전역 추천이면 null.
    candidate_count integer NOT NULL,         -- AI 에 실제로 보낸 후보 수 (상한 적용 후)
    created_at timestamp(6) NOT NULL
);

-- ── 아이템: 그 호출에서 나온 추천 결과 ───────────────────────────────────────
-- 프론트에 내려간 상위 N 건만이 아니라 AI 가 점수를 매긴 결과를 순위대로 남긴다.
--
-- ※ team_id 에 FK 를 걸지 않는다. 이건 시점 기록(로그)이라 팀이 나중에 삭제돼도 남아야 하고,
--   FK 가 있으면 TeamService.deleteTeam 이 로그 때문에 실패한다 (V8 에서 team_embeddings 로
--   같은 문제를 겪었다). 대신 조회 시 팀이 없을 수 있음을 전제한다.
--
-- ※ 컬럼명이 rank 가 아니라 rank_no 인 이유: rank 는 SQL 표준 예약어라 방언에 따라
--   따옴표 없이는 못 쓰는 경우가 생긴다. 애먼 데서 깨지느니 이름을 피한다.
CREATE TABLE user_to_team_recommendation_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id bigint NOT NULL,
    team_id bigint NOT NULL,
    rank_no integer NOT NULL,                 -- 1 부터. 점수 내림차순 순위.
    score double precision NOT NULL,
    label text,                               -- AI 가 만든 추천 근거 문구
    created_at timestamp(6) NOT NULL,
    CONSTRAINT uk_user_to_team_recommendation_items_rank UNIQUE (log_id, rank_no)
);

-- ── 외래키 ───────────────────────────────────────────────────────────────────
ALTER TABLE user_to_team_recommendation_logs
    ADD CONSTRAINT fk_user_to_team_recommendation_logs_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

-- 헤더가 지워지면 아이템도 함께 (아이템만 남으면 의미가 없다).
ALTER TABLE user_to_team_recommendation_items
    ADD CONSTRAINT fk_user_to_team_recommendation_items_log
    FOREIGN KEY (log_id) REFERENCES user_to_team_recommendation_logs (id) ON DELETE CASCADE;

-- ── 인덱스 ───────────────────────────────────────────────────────────────────
-- "이 사용자에게 최근 뭘 추천했나" 가 주 조회 패턴.
CREATE INDEX idx_user_to_team_recommendation_logs_user
    ON user_to_team_recommendation_logs (user_id, created_at DESC);
CREATE INDEX idx_user_to_team_recommendation_items_log
    ON user_to_team_recommendation_items (log_id, rank_no);
-- "이 팀이 얼마나 추천됐나" (팀 노출 분석용).
CREATE INDEX idx_user_to_team_recommendation_items_team
    ON user_to_team_recommendation_items (team_id);
